# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 23:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(10)])),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
