# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='coding_einsteiger',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='coding_fortgeschritten',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='elektronik',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='freitext',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendee',
            name='linux',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='loeten',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='medien_bearbeitung',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='roboter',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendee',
            name='wearables',
            field=models.CharField(blank=True, choices=[(b'yeah', b'Will ich machen'), (b'ez', b'Kann ich'), (b'nope', b'Interessiert mich nicht')], max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
